packages:
  - 'packages/*'
  - 'examples/*'

catalog:
  '@tailwindcss/postcss': 4.1.12
  '@tailwindcss/vite': 4.1.12
  '@types/react': 19.1.11
  '@types/react-dom': 19.1.8
  '@vitejs/plugin-react-swc': 4.0.1
  react: 19.1.1
  react-dom: 19.1.1
  postcss: 8.5.6
  tailwindcss: 4.1.12
  vite: 7.1.3

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - lefthook
