packages:
  - 'packages/*'
  - 'examples/*'

catalog:
  '@types/react': 19.1.11
  '@types/react-dom': 19.1.8
  react: 19.1.1
  react-dom: 19.1.1

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - lefthook
