packages:
  - packages/*
  - examples/*

minimumReleaseAge: 10080

catalog:
  '@tailwindcss/postcss': 4.1.14
  '@tailwindcss/vite': 4.1.14
  '@types/react': 19.2.1
  '@types/react-dom': 19.2.0
  '@vitejs/plugin-react-swc': 4.1.0
  postcss: 8.5.6
  react: 19.2.0
  react-dom: 19.2.0
  tailwindcss: 4.1.14
  vite: 7.1.9

ignoredBuiltDependencies:
  - sharp

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - lefthook
