packages:
  - packages/*
  - apps/*
  - examples/*

blockExoticSubdeps: true

catalog:
  '@tailwindcss/postcss': 4.2.2
  '@tailwindcss/vite': 4.2.2
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  '@vitejs/plugin-react': 6.0.1
  postcss: 8.5.8
  react: 19.2.4
  react-dom: 19.2.4
  tailwindcss: 4.2.2
  vite: 8.0.1
  vite-plus: 0.1.13
  vitest: 4.1.0

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - edgedriver
  - esbuild
  - geckodriver
  - sharp

minimumReleaseAge: 4320

onlyBuiltDependencies:
  - agent-browser

verifyDepsBeforeRun: install
