packages:
  - packages/*
  - apps/*
  - examples/*

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - react
  - react-dom
  - next
  - '@next/env'
  - '@funstack/static'
  - '@funstack/router'

catalog:
  '@tailwindcss/postcss': 4.2.0
  '@tailwindcss/vite': 4.2.0
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  '@vitejs/plugin-react-swc': 4.2.3
  postcss: 8.5.6
  react: 19.2.4
  react-dom: 19.2.4
  tailwindcss: 4.2.0
  vite: 7.3.1

ignoredBuiltDependencies:
  - sharp

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - lefthook
