packages:
  - packages/*
  - examples/*

minimumReleaseAge: 10080

catalog:
  '@tailwindcss/postcss': 4.1.16
  '@tailwindcss/vite': 4.1.16
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  '@vitejs/plugin-react-swc': 4.2.0
  postcss: 8.5.6
  react: 19.2.0
  react-dom: 19.2.0
  tailwindcss: 4.1.16
  vite: 7.1.9

ignoredBuiltDependencies:
  - sharp

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - lefthook
