name: Install
description: Sets up Node.js and runs install

runs:
  using: composite
  steps:
    - name: Install dependencies
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

    - name: Setup Node.js
      uses: actions/setup-node@dda4788290998366da86b6a4f497909644397bb2
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "kosakanoki@gmail.com"
        git config --global user.name "k8o"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Build
      shell: bash
      run: pnpm build
