name: Install
description: Sets up Node.js and runs install

runs:
  using: composite
  steps:
    - name: Install dependencies
      uses: pnpm/action-setup@b9e1dbc72ff7358f971cc0b7c62c7a0d83f1068b

    - name: Setup Node.js
      uses: actions/setup-node@65d868f8d4d85d7d4abb7de0875cde3fcc8798f5
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "kosakanoki@gmail.com"
        git config --global user.name "k8o"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Build
      shell: bash
      run: pnpm build
