name: Install
description: Sets up mise and runs install

runs:
  using: composite
  steps:
    - name: Setup mise
      uses: jdx/mise-action@v2
      with:
        cache: true

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "kosakanoki@gmail.com"
        git config --global user.name "k8o"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Build
      shell: bash
      run: pnpm build
